# Configuração do Prometheus para monitoramento
global:
  scrape_interval: 15s
  evaluation_interval: 15s
  external_labels:
    cluster: 'renum-production'
    environment: 'production'

# Regras de alerta
rule_files:
  - "alert_rules.yml"

# Configuração do Alertmanager
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          - alertmanager:9093

# Jobs de scraping
scrape_configs:
  # Prometheus self-monitoring
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']
    scrape_interval: 30s
    metrics_path: /metrics

  # API Principal
  - job_name: 'renum-api'
    static_configs:
      - targets: ['api:8000']
    scrape_interval: 15s
    metrics_path: /metrics
    scrape_timeout: 10s
    honor_labels: true
    params:
      format: ['prometheus']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: 'renum-api'

  # Node Exporter (métricas do sistema)
  - job_name: 'node-exporter'
    static_configs:
      - targets: ['node-exporter:9100']
    scrape_interval: 30s
    metrics_path: /metrics

  # Redis Exporter
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    scrape_interval: 30s
    metrics_path: /metrics

  # PostgreSQL Exporter
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    scrape_interval: 30s
    metrics_path: /metrics

  # Nginx Exporter
  - job_name: 'nginx'
    static_configs:
      - targets: ['nginx:9113']
    scrape_interval: 30s
    metrics_path: /metrics

  # Blackbox Exporter para health checks externos
  - job_name: 'blackbox-http'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - http://api:8000/health
        - http://nginx:80/health
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115

  # Monitoramento de serviços externos
  - job_name: 'external-services'
    metrics_path: /probe
    params:
      module: [http_2xx]
    static_configs:
      - targets:
        - https://api.whatsapp.com
        - https://api.telegram.org
        - https://gmail.googleapis.com
    relabel_configs:
      - source_labels: [__address__]
        target_label: __param_target
      - source_labels: [__param_target]
        target_label: instance
      - target_label: __address__
        replacement: blackbox-exporter:9115
    scrape_interval: 60s

  # Métricas customizadas da aplicação
  - job_name: 'renum-custom-metrics'
    static_configs:
      - targets: ['api:8000']
    scrape_interval: 15s
    metrics_path: /api/v1/metrics/prometheus
    bearer_token_file: /etc/prometheus/api-token
    honor_labels: true
    relabel_configs:
      - source_labels: [__name__]
        regex: 'renum_.*'
        action: keep

# Configuração de armazenamento
storage:
  tsdb:
    retention.time: 30d
    retention.size: 10GB
    wal-compression: true