// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ldfzypnyjqoyzqcnkcdy.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImxkZnp5cG55anFveXpxY25rY2R5Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTQ3OTQ1MDYsImV4cCI6MjA3MDM3MDUwNn0.a2EQ3iqXDkMYTuiIChz9GPgfZnMLgYbejGOCJ-QrYFw";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});